server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/j2ee?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.jlu.jtee.entity

logging:
  level:
    com:
      jlu:
        jtee:
          mapper: debug